### ISSUE TITLE
formula and compiled structure does not match

### ISSUE THREAD

**Issue by Zhuoying** [mpds-io/mpds-client#15]
Hi, I found a weird bug when using `MPDSDataRetrieval` to query structures.
When I use mpds.get_data for this entry 
```
[227,
 'S1002002',
 'LiNbO3',
 [5.2727, 5.2727, 13.8509, 90.0, 90.0, 120.0],
 167,
 [[0.3909, 0.0, 0.25], [0.0, 0.0, 0.214], [0.0, 0.0, 0.0]],
 ['O', 'Li', 'Nb']]
```
`MPDSDataRetrieval().compile_crystal(d[-4:],flavor='pmg')` generated structure is Li2NbO3. It does not match the formula of LiNbO3. I wonder which one is correct and if there is something that needs to be fixed. 

Thanks in advance!

**Comment by blokhin** [comment]
Hi, a quick look at the [entry](https://mpds.io/entry/S1002002) suggests that there might be a symmetry problem with the trigonal lattice that the `spglib` used by MPDS is unable to handle. On the other hand, `STRUCTURE TIDY` analysis done by the Pauling File editors (see multiplicity table) suggests that the original chemical formula Li2NbO3 is correct, whereas the refined formula is Li0.91NbO3. So the problem might be deeper than the symmetry handling.

Indeed, looking into the original article, Fig. 2, I see some interesting physics with the heavily disordered mobile Li ion, as well as the phase transition involving it, described by different ordering mechanisms. So I assume both the formulae are correct to a certain extent. I believe, a careful [electronic-structure modeling](https://optimade.science/?filter=chemical_formula_reduced%3D%22LiNbO3%22&page=1&limit=10&providers=mp,nmd) might help to understand what is going on here.

**Comment by Zhuoying** [comment]
Hi @blokhin thanks for the quick reply. I appreciate it!
I also took a look at both the entry and original paper after you mentioned them. It looks there is an order-disorder transition at high temp and Li occupied 0.5 of all possible sites leading to ~LiNbO3.
I can understand now why queried formula and compiled structure formula are different. However, it is the first entry when I use API to query by `{"classes":"perovskite, non-disordered"}`. So I supposed every entry should be `non-disordered`. 
Does that mean the disorder criteria is not always accurate and users need to take a deeper look?
Thanks~

**Comment by blokhin** [comment]
Well, _formally_ it was not reported as a disordered structure, so the criterion is fulfilled. Certainly I agree that the MPDS querying should be more physics-aware to account for such cases.

Anyway thanks for raising this issue! We will think how how to treat such a “hidden disorder”.
